### ISSUE TITLE
responseProps

### ISSUE THREAD

**Issue by sauyeung** [RobinTail/express-zod-api#1067]
### Discussed in https://github.com/RobinTail/express-zod-api/discussions/1049

<div type='discussions-op-text'>

<sup>Originally posted by **sauyeung** July 12, 2023</sup>
I am testing an endpoint that uses the express-rate-limit middleware, and pass `responseProps` to `testEndpoint` as follows:
>          responseProps: {
>             ip: '192.168.1.1',
>             setHeader: (name: string, value: string) => {
>               console.log(name + ': ' + value);
>             }
>           }
The `responseMock` object does have these attributes added when testing cases of this endpoint that are expected to succeed; but not added when they are expected to fail; and got _response.setHeader is not a function_ error. Is this an issue or expected? If it's expected, are there any ways to make it work?</div>

**Comment by RobinTail** [comment]
> when they are expected to fail

Could you please clarify what kind of failure do you test, @sauyeung ?
Is it schema-violation error? Or is it some error thrown within the handler?

**Comment by RobinTail** [comment]
> and got response.setHeader is not a function

is it possible that you're calling `setHeader` in a chain?

like `response.someMethod().anotherMethod().setHeader()` ?

**Comment by RobinTail** [comment]
I'm going to release v11.5.0, that will have `setHeaders` mocked. So you no longer need to mock it.
I hope it will help.
If not, please let me know

**Comment by sauyeung** [comment]
Thanks for you response, Robin! Let me give you more details on what I am doing and see if just adding `setHeaders` mock will help. I installed the `express-rate-limit` package and use it as one of the middleware.

`import rateLimit from 'express-rate-limit';

// for v1/auth/verify-access-code
export const verifyAccessCodeLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour
  max: 5, // limit to 5 calls per window
  statusCode: 429, // status code
  message: 'Too many access code verifications, please try again after an hour',
  standardHeaders: true, // return rate limit info in the `RateLimit-*` headers
  legacyHeaders: false // disable the `X-RateLimit-*` headers
});


export const verifyAccessCode = v1EndpointsFactory
  .addExpressMiddleware(verifyAccessCodeLimiter)
  .build({
  ...
});`

I test the endpoint as follows:

`const { responseMock, loggerMock } = await testEndpoint({
  endpoint: verifyAccessCode,
  requestProps: {
    method: 'POST',
    ip: '192.168.1.1',
    body: {
      ...body,
      code: accessCode 
    }
  },
  responseProps: {
    setHeader: (key: string, value: string) => {
      console.log(`setHeader: ${key}=${value}`);
    }
  } 
});`

It is the code in the `express-rate-limit` package calling `header`, `send`, etc.

Here is the stack trace:

`    TypeError: response.send is not a function

      at Object.handler (node_modules/express-rate-limit/dist/index.cjs:201:18)
      at node_modules/express-rate-limit/dist/index.cjs:315:17
      at async /Users/sauyeung/flock-api/node_modules/express-rate-limit/dist/index.cjs:221:5`
