### ISSUE TITLE
`ez.upload()` does not work with `.attachRouting()`

### ISSUE THREAD

**Issue by john-schmitz** [RobinTail/express-zod-api#1091]
Hello, thank you so much for your library; it really helped.
in the following snippet, I am creating an express application and attaching an `express-zod-api` route to my application.

```typescript
import {
  Routing,
  attachRouting,
  createConfig,
  createServer,
  defaultEndpointsFactory,
  ez,
  ZodUploadDef,
} from "express-zod-api";
import { createHash } from "crypto";
import express from "express";

const app = express();

const config = createConfig({
  app,
  server: {
    listen: 8090,
    upload: true,
  },
  startupLogo: false,
  cors: true,
  logger: {
    level: "debug",
    color: true,
  },
});

import { z } from "zod";

const fileUploadEndpoint = defaultEndpointsFactory.build({
  method: "post",
  tag: "files",
  description: "Handles a file upload.",
  input: z
    .object({
      avatar: ez
        .upload()
        .refine(
          (file) => file.mimetype.match(/image\/.+/),
          "Should be an image"
        ),
    })
    .passthrough(),
  output: z.object({
    name: z.string(),
    size: z.number().int().nonnegative(),
    mime: z.string(),
    hash: z.string(),
    otherInputs: z.record(z.any()),
  }),
  handler: async ({ input: { avatar, ...rest } }) => {
    return {
      name: avatar.name,
      size: avatar.size,
      mime: avatar.mimetype,
      hash: createHash("sha1").update(avatar.data).digest("hex"),
      otherInputs: rest,
    };
  },
});

const routing: Routing = {
  v1: {
    upload: fileUploadEndpoint,
  },
};

const { notFoundHandler, logger } = attachRouting(config, routing);
app.listen(8090);

logger.info("Glory to science!");

```

By curling into this endpoint:
`curl --request POST   --url http://localhost:8090/v1/upload   --header 'Content-Type: multipart/form-data'   --form avatar=@/home/john/Downloads/IMG_20230807_175615.jpg`

I get the following response:
`{"status":"error","error":{"message":"avatar: Expected file upload, received undefined"}}`

Am I missing something? Can I provide you more information on how to reproduce this issue?

**Comment by RobinTail** [comment]
Hello @john-schmitz .

> Am I missing something?

Yes.

```ts
const config = createConfig({
  app,
  server: {
    listen: 8090,
    upload: true,
  },
  // ...
```

You're using both `app` and `server` entries in your config, while `app` is YOUR app for the further usage of `.attachRouting()` method, and the `server` is only used by `.createServer()` method.

As you may already realise, the `upload: true` feature inside `server` affects only the `createServer`-approach, not `.attachRouting()` one. Please be informed on what exactly it does:

https://github.com/RobinTail/express-zod-api/blob/a57c350c0f170b3baf73f30a42364aea93d3ee95/src/server.ts#L88-L96

It creates a multipart body parsing middleware for the server being created by `createServer` method.

Therefore, in your case, having your OWN app, you need to do a similar thing — you need to install `express-fileupload`, create a multipart body parsing middleware and attach it to YOUR `app`. Most likely before calling `attachRouting`.

I hope this helps — let me know.

**Comment by RobinTail** [comment]
Don't forget to remove `server` from your `config` after that, you don't need it in this case.

**Comment by RobinTail** [comment]
Should be like this, @john-schmitz :

```ts
import fileUpload from "express-fileupload"

const app = express();
const multipartParser = fileUpload({
       // ...
       abortOnLimit: false, 
       parseNested: true, 
});
app.use( multipartParser );

const config = createConfig({
  app,
  startupLogo: false,
  cors: true,
  logger: {
    level: "debug",
    color: true,
  },
});
```

**Comment by RobinTail** [comment]
I hope this will help you to resolve the issue.
If not, please open another one.
