### ISSUE TITLE
Specifying input headers

### ISSUE THREAD

**Issue by andnilsson** [RobinTail/express-zod-api#1180]
I can´t find any way to specify variables in the request header the same way we can do it with params or query.
InputSources in createConfig doesn´t seem to support it like this:

`inputSources:{
      get: ["query", "params", "headers"],
    }`

And even if it´s possible to to it with the security prop on middleware like this:
`
security: {
    // this information is optional and used for generating documentation
    and: [
      { type: "input", name: "key" },
      { type: "header", name: "token" },
    ],
  },
`

I really don´t want this header to be specified as "security"

Is there any way to do this?

**Comment by andnilsson** [comment]
To be more clear, I´m looking for a way to specify input like this x-header-param open-api snippet:

```
/path:
    get:
      parameters:
        - name: x-header-param
          in: header
          required: true
          schema:
            type: string
        - name: otherProp
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponeDefinition'
```

**Comment by RobinTail** [comment]
You'd need to make a middleware, that inspects the request headers. The middleware should return an object that becomes "options" parameter for the endpoint's handler. This way you can provide the data acquired from headers to the endpoints, in case the headers carry out more than authentication. @andnilsson

**Comment by RobinTail** [comment]
> To be more clear, I´m looking for a way to specify input like this x-header-param open-api snippet

Currently headers are not considered as an input source for request parameters, but only as a way of authentication, that's why they are only available for describing as a part of security schemas in OpenAPI.
I understand your need, though I never experienced such a requirement. I need to check if OpenAPI even allows such ways of describing parameter location as header.

**Comment by RobinTail** [comment]
yeah, @andnilsson , I found it in the specification.
OpenAPI definitely has `in: header`.
I'd consider this as a feature request in this regard.

![image](https://github.com/RobinTail/express-zod-api/assets/13189514/ca2759e9-cf76-44ad-9f5a-fafca56d4434)

**Comment by RobinTail** [comment]
If implementing this feature, it's going to be limited to the custom header only (those beginning with `X-`), and most likely they will be converted to the lower case, @andnilsson 

https://swagger.io/docs/specification/describing-parameters/#header-parameters

**Comment by andnilsson** [comment]
It sure does, awesome!

**Comment by RobinTail** [comment]
@andnilsson , the feature released in version 12.2.0 🚀

**Comment by andnilsson** [comment]
very impressive :D

**Comment by RobinTail** [comment]
All headers (not just `x-` prefixed) made accessible as input source in v22.0.0 and detectible from `Middleware::security` in v22.2.0
