### ISSUE TITLE
Multiple servers in Swagger

### ISSUE THREAD

**Issue by bobgubko** [RobinTail/express-zod-api#1195]
Is there a way to set multiple `servers` in generated OpenAPI's yaml? Right now only string can be provided for `serverUrl` in `Documentation`. Would be nice to pass array of strings, e.g.:

```
const yamlString = new Documentation({
  routing,
  config,
  version: "1.0.0",
  title: "Test",
  serverUrl: [
    `http://127.0.0.1`,
    `https://prod.example.com`,
  ]
}).getSpecAsYaml()
```

**Comment by RobinTail** [comment]
Currently you can use `.addServer()` method before calling `.getSpecAsYaml()`.
But it's a good idea to support an array during the instantiation of `Documentation`, @bobgubko
