### ISSUE TITLE
Export request/response types from generated client

### ISSUE THREAD

**Issue by bobgubko** [RobinTail/express-zod-api#1219]
Is there a way to add `export` to request and response types to the client generated via `Integration`?

**Comment by RobinTail** [comment]
It seems to that they are already exported, @bobgubko 

https://github.com/RobinTail/express-zod-api/blob/3ae174ac000db2a9e628f9fae1f55c8084078b83/example/example.client.ts#L107-L123

Or maybe I don't understand what you mean.
Please clarify.

**Comment by bobgubko** [comment]
So if I need to access `GetV1UserRetrieveResponse`, I can access it as `Response["get /v1/user/retrieve"]`?

**Comment by RobinTail** [comment]
exactly, @bobgubko

**Comment by RobinTail** [comment]
@bobgubko , that's how `Provider` type works.
You can make your own helper similarly.

https://github.com/RobinTail/express-zod-api/blob/3ae174ac000db2a9e628f9fae1f55c8084078b83/example/example.client.ts#L141-L145

**Comment by bobgubko** [comment]
Thanks for clarifying!
