### ISSUE TITLE
incorrect pattern field for openapi

### ISSUE THREAD

**Issue by elee1766** [RobinTail/express-zod-api#1458]
so in my generated openapi schema, i noticed that there was "/" surrounding my regex, which ends up rendering incorrectly in swagger-ui

i traced it to this line in the documentation builder in depictString.

https://github.com/RobinTail/express-zod-api/blob/c39f7397eb0c9ff9e8ee6aaf5f940f6916130011/src/documentation-helpers.ts#L464

so it uses the format `/${regex.source}/${regex.flags}`, however looking here: https://swagger.io/docs/specification/data-models/data-types/#pattern it seems that it just wants `${regex.source}`, and oas3/3.1 does not support flags

https://262.ecma-international.org/5.1/#sec-15.10.1 it looks like bnf for regexp here does not include the wrapping `/` and flags

i think the right answer here is to just change this line to ```result.pattern = `${regex.source}` // result.pattern = regex.source``` ?

**Comment by RobinTail** [comment]
Confirmed: https://github.com/OAI/OpenAPI-Specification/issues/1985
Thank you for noticing this issue, @elee1766

**Comment by RobinTail** [comment]
> rendering incorrectly in swagger-ui

@elee1766 , could you please install the version `16.2.2-beta1` and tell me if it fixes the issue?

**Comment by elee1766** [comment]
looks good! thanks !!!
