### ISSUE TITLE
OpenApi yaml spec has wrong minimum value for doubles

### ISSUE THREAD

**Issue by kotsmile** [RobinTail/express-zod-api#1517]
# Description

If output scheme has `z.number()` minimum value in openapi sets `Number.MIN_VALUE` (> 0), but in reality floats can be negative and zero

## Expected

`z.number()` must generate openapi with correct min values

## Reproduction
1. Create handler with output schema like `{ value: z.number() }`
2. Initialize new `Documentation` object with route including handler from step.1 
3. Call `getSpecAsYaml` in `Documentation` object
4. Type description contains min specification with `minimum: 5e-324`

- Node.js version: 18.16.1
- `express-zod-api` version: 16.5.2

**Comment by kotsmile** [comment]
https://github.com/RobinTail/express-zod-api/blob/ec2471849daad1db711377bc0acab57f28a00dd5/src/documentation-helpers.ts#L516

**Comment by kotsmile** [comment]
![image](https://github.com/RobinTail/express-zod-api/assets/40324517/c5981016-862c-42bb-b605-728f064d4e6c)

definition of `Number.MIN_VALUE`

Suggestion to replace it with `Number.MIN`

**Comment by RobinTail** [comment]
Agree.
Perfect catch, @kotsmile 
Thank you!

In case you have an idea on what should be the right value in this case, please let me know.

**Comment by RobinTail** [comment]
Probably this 

```ts
-Number.MAX_VALUE
```

**Comment by kotsmile** [comment]
@RobinTail thank you for so fast fix!

**Comment by RobinTail** [comment]
🚀 fixed in v16.5.3, @kotsmile 
Thank you for the contribution!
