### ISSUE TITLE
tsc error when trying to build using the getting started instructions

### ISSUE THREAD

**Issue by brainthinks** [RobinTail/express-zod-api#1684]
# Description

I followed the getting started instructions from the master branch README in a new project. When running tsc on my project, I received the following:

```
$ tsc
node_modules/express-zod-api/dist/index.d.ts:1:25 - error TS2307: Cannot find module 'compression' or its corresponding type declarations.

1 import compression from 'compression';
                          ~~~~~~~~~~~~~

node_modules/express-zod-api/dist/index.d.ts:3:37 - error TS2307: Cannot find module 'express-fileupload' or its corresponding type declarations.

3 import * as express_fileupload from 'express-fileupload';
                                      ~~~~~~~~~~~~~~~~~~~~

node_modules/express-zod-api/dist/index.d.ts:4:41 - error TS2307: Cannot find module 'express-fileupload' or its corresponding type declarations.

4 import express_fileupload__default from 'express-fileupload';
                                          ~~~~~~~~~~~~~~~~~~~~

node_modules/express-zod-api/dist/index.d.ts:8:21 - error TS2307: Cannot find module 'winston' or its corresponding type declarations.

8 import Winston from 'winston';
                      ~~~~~~~~~

node_modules/express-zod-api/dist/index.d.ts:523:40 - error TS2344: Type '"body" | "headers" | "query" | "params" | "files"' does not satisfy the constraint 'keyof Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
  Type '"files"' is not assignable to type 'keyof Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.

523 type InputSource = keyof Pick<Request, "query" | "body" | "files" | "params" | "headers">;

```

## Expected

I expected the getting started instructions to result in a successful tsc build.

## Reproduction

Copy and paste the code snippets in the getting started section of the README.

## Context

- Node.js version: 20.9.0
- `express-zod-api` version: 17.7.0

Also worth noting that i'm attempting to pass an instance of Pino rather than letting express-zod-api instantiate a winston logger for me.

**Comment by brainthinks** [comment]
In order to unblock myself, I ran the following:

```
yarn add -D @types/compression @types/express-fileupload @types/winston
```

I may have missed something, and installing these types may not be the desired fix, but it's at least letting me progress.

**Comment by RobinTail** [comment]
@brainthinks ,

Your dev environment tries to compile/validate `node_modules`.
Please ensure having the following option in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "skipLibCheck": true,
  }
}
```

Or consider extending from a recommended base:
https://github.com/tsconfig/bases

Please let me know if this worked.

**Comment by RobinTail** [comment]
> express-zod-api version: 17.7.0
> Also worth noting that i'm attempting to pass an instance of Pino rather than letting express-zod-api instantiate a winston logger for me.

Great choice!
Consider version `^18.0.0-beta2` — it has no dependency on `winston` at all, @brainthinks 

https://github.com/RobinTail/express-zod-api/blob/make-v18/CHANGELOG.md#v1800

**Comment by RobinTail** [comment]
Managed to reproduce the issue.
Not a bug, but rather lack of Typescript configuration.
I will mention it in the documentation.

**Comment by brainthinks** [comment]
Wow, thank you for the immediate response and update! I had planned to offer a PR to you today, but you beat me to it.

Regarding the need to include the `skipLibCheck` configuration, this will indeed "fix" the issue and unblock newcomers like myself. I think it's worth noting though that I haven't needed to do this for any other dependency (yet). I do think that asking people to set it is a reasonable approach, even more so since this is the way it is configured in the [recommended base](https://github.com/tsconfig/bases). In my opinion, a small section in the README for installing the necessary deps to not need to skip lib checks would be helpful, but I can also understand leaving that out as an exercise to the readers (like myself) who want the ability to configure their project in a way that differs from what you recommend. If you agree that mentioning the installation of the types as an alternative is desirable, I'm happy to submit a PR for it.

Either way, thanks!

**Comment by RobinTail** [comment]
It seems to be fine now, @brainthinks , the requirement on the necessary types is already there:

| v18 | v17 |
|--------|--------|
| ![2024-04-22_23-08-01](https://github.com/RobinTail/express-zod-api/assets/13189514/fda4b8b7-c4cb-48e4-b39b-9566b66d16c2) | ![image](https://github.com/RobinTail/express-zod-api/assets/13189514/a0369b1b-3a04-49b0-ac1f-7b5b9bc70b90) | 

The ones that you had to install to unblock yourself

> yarn add -D @types/compression @types/express-fileupload @types/winston

Are not necessary when `skipLibCheck` is enabled, because `winston`, `compression` and `express-fileupload` are optional peer dependencies.

But in case I didn't understand something, feel free to make a PR.

**Comment by brainthinks** [comment]
Submitted - https://github.com/RobinTail/express-zod-api/pull/1696

This is what I would have liked to see in the getting started section, for compatibility with the way I/we set up projects. I understand that this may not align with your vision, and adds slight overhead / maintenance burden.

Thanks for taking the time to look at this.

**Comment by brainthinks** [comment]
I closed the PR with a comment. I think you're right that this should be a recommended tsconfig setting, and there's no need to document the installation of the existing types.

Thank you!
