### ISSUE TITLE
Is it possible to add custom documentation generation for my custom zod types

### ISSUE THREAD

**Issue by kotsmile** [RobinTail/express-zod-api#1746]
Please create a discussion in the Ideas section instead:
https://github.com/RobinTail/express-zod-api/discussions/new?category=ideas

**Comment by RobinTail** [comment]
https://github.com/RobinTail/express-zod-api/discussions/1470

Not yet, @kotsmile .
But maybe I will implement this feature in v19, it will be easier there.

**Comment by RobinTail** [comment]
🚀 Now available in version 19.1.0, @kotsmile
