### ISSUE TITLE
Duplicated headers in request body in generated docs (POST, PATCH, etc.)

### ISSUE THREAD

**Issue by boarush** [RobinTail/express-zod-api#1768]
# Description

When specifying custom headers in GET endpoints, the generated documentation is correctly built with the header field separate from the query params. In case of other HTTP Verbs (POST, PATCH, etc.), the documentation incorrectly includes the header in the request body instead of making a header field, though after specifying the `inputSources` in the `config`, request works in both cases, including the value in the request body and not in the headers OR including it in the headers and not in the request body.

## Expected

Generated documentation should correctly specify the field as a header in case of POST and other HTTP Verbs.

## Reproduction

Sample Repo:
https://github.com/boarush/express-zod-api/tree/bug/missing-headers

Have forked this repo and modified the example GET, POST and PATCH endpoints for in the user section.

## Context

- Node.js version: 20.12.2
- `express-zod-api` version: 19.1.0

Thank you for the wonderful work! Really simple working with the library!

**Comment by RobinTail** [comment]
I assume this commit is what illustrates the issue

https://github.com/RobinTail/express-zod-api/commit/ccc098e6621f2d09961900731d0e6ebcb2cef9db

**Comment by RobinTail** [comment]
@boarush , this line controls the appearance of the parameter in headers when you generate the documentation:

https://github.com/RobinTail/express-zod-api/blob/78ea9a8c8d4ecd299b5c90a18ecfcb55d5315f9f/src/documentation-helpers.ts#L705-L706

Which means, as described in README, you should:

1. Enable `headers` in `inputSources`;
2. The header should start with `x-`.

> though after specifying the inputSources in the config, request works in both cases

So... What's the issue with setting `inputSources`?
Headers in input is the opt-in feature that you can enable that way.
Please clarify.

**Comment by boarush** [comment]
<img width="1920" alt="Screenshot 2024-05-16 at 01 19 21" src="https://github.com/RobinTail/express-zod-api/assets/56695832/10a5a67a-224e-41b5-b083-e38f6e959743">
<img width="1920" alt="Screenshot 2024-05-16 at 01 18 15" src="https://github.com/RobinTail/express-zod-api/assets/56695832/00603975-d104-4669-b5ed-800c74d0c435">
<img width="1920" alt="Screenshot 2024-05-16 at 01 18 01" src="https://github.com/RobinTail/express-zod-api/assets/56695832/afc60454-8c63-4ab9-9ac2-8b3b5262d0ed">
<img width="1920" alt="Screenshot 2024-05-16 at 01 22 05" src="https://github.com/RobinTail/express-zod-api/assets/56695832/7943bfd5-83aa-4948-b6b1-b4738ea5fedf">


In the screenshots, you can see that I have specified the `x-request-id` header as input for both the GET and POST endpoint, however, one shows up correctly as a header in the swagger doc and one only as the part of request body. 

Does this example make the problem clear?

**Comment by RobinTail** [comment]
Ok. I need to make a test...

**Comment by RobinTail** [comment]
On your screenshots both actually appear wrong, @boarush .
Even for GET request it says that the placement is `query`, but it should be `header`

![image](https://github.com/RobinTail/express-zod-api/assets/13189514/cfb795b0-3833-4a6e-84ca-b5e3f2d2eae1)

And that's very confusing, because for that case I already have a test.

**Comment by boarush** [comment]
I think I mixed up the screenshots, those were for when I was not including the `inputSources`. Following are for when I am including the `inputSources`:
<img width="1920" alt="Screenshot 2024-05-16 at 01 33 50" src="https://github.com/RobinTail/express-zod-api/assets/56695832/4a15e6ae-9c74-41dd-8430-9951a944e700">
<img width="1920" alt="Screenshot 2024-05-16 at 01 33 44" src="https://github.com/RobinTail/express-zod-api/assets/56695832/028548fe-8cfd-493f-8134-479ff715e067">

GET is absolutely correct, POST is showing double fields.

**Comment by RobinTail** [comment]
I see, it's duplicated, @boarush 
Present in both "parameters" and the "body"

![image](https://github.com/RobinTail/express-zod-api/assets/13189514/62b6be7d-04ba-4e6a-a94c-55497a5cffa1)

**Comment by RobinTail** [comment]
[Confirmed](https://github.com/RobinTail/express-zod-api/pull/1769#discussion_r1602192826), @boarush 

Thank you so much for informing me and for the detailed explanation.

**Comment by boarush** [comment]
I think that when getting the requestBody here, it needs to exclude the headers if they're enabled.

https://github.com/RobinTail/express-zod-api/blob/78ea9a8c8d4ecd299b5c90a18ecfcb55d5315f9f/src/documentation.ts#L222-L233

**Comment by RobinTail** [comment]
🚀 Should be fixed in v19.1.1, @boarush 
In case it's not, please open another issue.
Thank you once again for your contribution!
