### ISSUE TITLE
Customising logger with winston erroring out in v19

### ISSUE THREAD

**Issue by boarush** [RobinTail/express-zod-api#1772]
# Description

Following the instructions in the [README](https://github.com/RobinTail/express-zod-api/blob/master/README.md) for customising the logger for winston, I encounter an error on calling the `child` method on `parent` in the method passed to `childLoggerProvider`.

Here is the error that I receive:
```zsh
➜  project git:(main) pnpm run start

> project@1.0.0 start /Users/sourabh/Experiments/project
> tsx index.ts

2024-05-16T16:28:29.251Z info: Listening 8090
/Users/sourabh/Experiments/project/config.ts:21
        return parent.child({ requestId: Math.random() * 100000 });
                      ^


TypeError: parent.child is not a function
    at Object.childLoggerProvider (/Users/sourabh/Experiments/project/config.ts:21:23)
    at <anonymous> (/Users/sourabh/Experiments/project/node_modules/.pnpm/express-zod-api@19.1.1_express@4.19.2_http-errors@2.0.0_typescript@5.4.5_zod@3.23.8/node_modules/express-zod-api/dist/index.js:5:10350)
    at Layer.handle [as handle_request] (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:328:13)
    at /Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sourabh/Experiments/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:328:13)

Node.js v20.12.2
 ELIFECYCLE  Command failed with exit code 1.
```

However the logger works when you directly return `logger.child()` instead of `parent.child()`.

## Expected

Should be able to return using the `parent.child()` as specified in the README, worked as expected in v18 

## Reproduction

Here's a sample repo https://github.com/boarush/winston-eza-example. Try using the `/status` endpoint when returning the `parent.child()` and `logger.child()`.Former errors and latter works.

https://github.com/boarush/winston-eza-example/blob/660eec632ebef55f71b2add1e8d0c9b6706a3b13/config.ts#L19-L22

## Context

- Node.js version: 20.12.2
- `express-zod-api` version: 19.1.1

**Comment by RobinTail** [comment]
Seems to be similar to #1605 , @boarush 

![image](https://github.com/RobinTail/express-zod-api/assets/13189514/7cb64458-9e09-4667-a439-94da68765996)

Trying to figure out why

**Comment by RobinTail** [comment]
Need to check prototype in `isBuiltinLoggerConfig`.

Confirmed, @boarush 
Thank you for reporting this.

**Comment by boarush** [comment]
Was trying to figure it out myself, couldn't really narrow it down 😅

**Comment by RobinTail** [comment]
The issue comes from the the problem of distinguishing a built-in logger config from an instance of actual logger.
I think I'm going to apply an inverted logic there, instead of `isBuiltinLoggerConfig()` it will be `isActualLogger()`, and use expression like this to check for the presence of a logging method both in the supplied argument and its prototype (class instance case).

```ts
"debug" in logger || "debug" in Object.getPrototypeOf(logger)
```

**Comment by boarush** [comment]
I think this is general enough to not break popular logging libraries.

**Comment by RobinTail** [comment]
No-no, it does not interfere in their operation. It's just a check of the object shape.

**Comment by boarush** [comment]
I think you misunderstood me, I am agreeing with what you suggested.

**Comment by RobinTail** [comment]
Ok, thank you.
I checked the documentation `in` on the `logger` should actually be enough, since it does check the prototype chain.

**Comment by RobinTail** [comment]
Checked this statement

> worked as expected in v18

The issue is present in v18.

**Comment by boarush** [comment]
Trying it my example repo with the latest v18 release, it worked. Not sure about other cases though.

**Comment by boarush** [comment]
@RobinTail I had also been using it in production with Winston specifically with v18. Didn't really face any issue or crashes.

**Comment by RobinTail** [comment]
🚀 Should be fixed in v19.1.2 , @boarush 
I tested it on your repo.
Thank you once again for your contribution!
I highly appreciate it.

**Comment by boarush** [comment]
Thanks for the speedy fix!

**Comment by boarush** [comment]
@RobinTail Another question, with winston, I'm only able to use 4 severity (debug, info, warn and error), all others don't work. How do I enable those for it? Have tried setting the `levels` config in `winston.createLogger`, and then using the generic `logger.log` with different levels, but it straight up ignores the logs for any severity other than these four.

**Comment by RobinTail** [comment]
You need to set both `levels` and `level`.
Last acts as a filter (ignores what's below it), @boarush

**Comment by RobinTail** [comment]
@boarush , configuring winston is not easy, so I moved from it.
But you can check out how it was configured in v17 for inspiration

https://github.com/RobinTail/express-zod-api/blob/a6ae0640259f53814e330d3ddd52a556b28e22a2/src/logger.ts#L98-L110

**Comment by boarush** [comment]
Yep, it works, thanks a lot again!
