### ISSUE TITLE
Catch errors in testMiddleware function

### ISSUE THREAD

**Issue by williamgcampbell** [RobinTail/express-zod-api#2153]
It's common for middleware to throw exceptions when validating auth tokens or other request information. When this happens, the mocks available within `testMiddleware` won't be returned and can't be used to confirm behavior. This makes it difficult to test behavior of anything that happened up to the point of failure. For example:

```javascript
import { z } from "zod";
import { Middleware, testMiddleware } from "express-zod-api";

const middleware = new Middleware({
  input: z.object({ test: z.string() }),
  handler: async ({ options, input: { test }, logger }) => {
     logger.info("logging something");
     throw new Error("something went wrong");
  },
});

// EXCEPTION THROWN HERE
const { output, responseMock, loggerMock } = await testMiddleware({
  middleware,
  requestProps: { method: "POST"},
  options: { prev: "accumulated" }, 
});
expect(loggerMock._getLogs().info).toHaveLength(1);  
```

To implement this we could provide an extra field to the function to indicate the intention of getting an error response back.  Something like:
```javascript
const { output, responseMock, loggerMock, error } = await testMiddleware({ 
  middleware,
  requestProps: { method: "POST"},
  options: { prev: "accumulated" }, 
  catchErrors: true, // when true will catch errors thrown by middleware and return them in the response
});
expect(loggerMock._getLogs().info).toHaveLength(1);
```

**Comment by RobinTail** [comment]
Is there anything why you can not do this:

```ts
await expect(
  () => testMiddleware()
).rejects.toThrow("something went wrong")
```

@williamgcampbell ?

**Comment by RobinTail** [comment]
My point is that you don't need `catchErrors: true` because there are already established methods of testing frameworks for asserting expectations on thrown errors.

**Comment by williamgcampbell** [comment]
```
await expect(
  () => testMiddleware( /* ... */ )
).rejects.toThrow("something went wrong");

// and then check logs too
expect(loggerMock._getLogs().info).toHaveLength(1);
```
How do you gain access to `loggerMock`? It is initialized and returned by `testMiddleware`.

**Comment by RobinTail** [comment]
Ah!
I get what you mean now, thank you for clarifying the problem, @williamgcampbell

**Comment by RobinTail** [comment]
> and return them in the response

it's a good idea, but I'd recommend to devote to consumer to decide how exactly that should happen.
So that it would be configurable.

Therefore, I'm suggesting to extend your idea slightly, @williamgcampbell :

```diff
- catchErrors?: boolean
+ onError?: (params: {
+   error: Error;
+   responseMock: ReturnType<typeof makeResponseMock>;
+ }) => void | Promise<void>;
```

So, that `onError` will act BOTH as a flag for catching AND as an implementation of responding with the error somehow.
In basic scenario it can be this:

```ts
onError: ({responseMock, error}) => responseMock.end(error.message)
```

What do you think?

**Comment by RobinTail** [comment]
Actually... there is another option.
We can use `configProps.errorHandler || defaultResultHandler` for that purpose.

**Comment by RobinTail** [comment]
Here is my final implementation, @williamgcampbell  in #2154 : 

https://github.com/RobinTail/express-zod-api/blob/4193ecaf740146d8ae5767b8f1d5ede426ffa486/src/testing.ts#L147-L150

I believe it should solve the issue for your case.
Let me know how you feel about it.

**Comment by RobinTail** [comment]
🚀 v20.20.0, @williamgcampbell
