### ISSUE TITLE
Error in frontend client usage exemple

### ISSUE THREAD

**Issue by HenriJ** [RobinTail/express-zod-api#2177]
# Description

The usage example in the generated client tries to find out if the response should be parsed as JSON or text using this line of code:
 ```
const parser = `${method} ${path}` in jsonEndpoints ? "json" : "text";
 ```

But `path` in this context is not a `MethodPath` but the path where the parameters have already been replaced by their value. Because of that, the "json" parser will never be selected

## Expected

It's not clear to me what the cleanest fix would be. I suppose `Implementation` could accept a 4th param that would be the original `MethodPath` ?

## Reproduction

Try to use the generated client with a JSON endpoint that has a path parameter

## Context

- Node.js version: 22
- `express-zod-api` version: 20.21.1

## Additional context

Love this lib! Really incredible work!

**Comment by RobinTail** [comment]
Hello @HenriJ , and thank you for donation.

Could you please clarify:

> But path in this context is not a MethodPath but the path where the parameters have already been replaced by their value.

why do you think that params are already replaced in `path`?

```ts
  const hasBody = !["get", "delete"].includes(method);
  const searchParams = hasBody ? "" : `?${new URLSearchParams(params)}`;
  const response = await fetch(`https://example.com${path}${searchParams}`, {
    method: method.toUpperCase(),
    headers: hasBody ? { "Content-Type": "application/json" } : undefined,
    body: hasBody ? JSON.stringify(params) : undefined,
  });
  const parser = `${method} ${path}` in jsonEndpoints ? "json" : "text";
```

**Comment by RobinTail** [comment]
Good point... checking why it still works...

**Comment by RobinTail** [comment]
Thank you for reporting this, @HenriJ .
And for the donation.
It seems that I missed the path parameters case in my tests.

**Comment by RobinTail** [comment]
In order to preserve the backwards compatibility, the suggested Implementation will use the `content-type` header of the actual response instead of `jsonEndpoints` dictionary.

**Comment by RobinTail** [comment]
🚀  v20.21.2, @HenriJ 
Thank you for the contribution
