### ISSUE TITLE
Direct access to endpoint handler

### ISSUE THREAD

**Issue by bitlab-code** [RobinTail/express-zod-api#432]
Hi and first of all thanks for `express-zod-api`.
To avoid redundant code it would be useful in my case to reuse an endpoint handler.
I explain better the use case, suppose you have two endpoints:
- `api/company/create` that create a company record and the owner profile
- `api/profile/create` that create a profile in the company, regardless of its role.

Calling the first endpoint I have to provide also the data to create the first profile, so in the first endpoint's handle I would like to use the functionality offered by the second endpoint.
I know that I can workaround this by export the handle function directly and use it, but in this case I will lose some features like the parsing of the input and the output, access to options, etc.

do you have any suggestions?
Thanks

**Comment by RobinTail** [comment]
My suggestion is to extract the profile creation logic (the one that repeats for the both endpoints) to another function with well typed arguments. Then you can call this function as needed from the both endpoints' handlers.

```typescript
const createProfile = (params: ProfileType) => { /* ... */ }

const createCompanyEndpoint = factory.build({
  /* ... */
  handler: async () => {
    // create company record, some code here:
    // ...
    createProfile({ /* ... */ });
  }
});

const createProfileEndpoint = factory.build({
  /* ... */
  handler: async () => {
    createProfile({ /* ... */ });
  }
});
```

This way you don't need to deal with endpoint handlers directly. More than that, handlers do operate input data, and you don't have to adjust to it.

@bitlab-code

**Comment by bitlab-code** [comment]
I was coming to the same conclusion, it is more appropriate to split the code further.
Thank you @RobinTail
Close this.
