### ISSUE TITLE
Nested top level refinements

### ISSUE THREAD

**Issue by kirdk** [RobinTail/express-zod-api#662]
It would be great to have the possibility to use the .superRefine() method in the endpoint's inputs. It will allow validating the input object in a more advanced way and return all issues found. To build the OpenAPI spec it's possible to use .InnerType() I think.

**Comment by RobinTail** [comment]
@kirdk ?

**Comment by kirdk** [comment]
Dear @RobinTail you are right, I checked 8.3.0 and .refine() is working as well as .superRefine(). The problem appears only if we use two or more refinements:
![image](https://user-images.githubusercontent.com/12613557/198219538-bd74abbf-a532-4278-83a9-47675b127a51.png)

For instance, when you are trying to split the validation code to reuse some of the functions, you need to use several refinements to combine rules that come from different functions.

**Comment by RobinTail** [comment]
I found the way to fix it, @kirdk 
Thank you

**Comment by RobinTail** [comment]
@kirdk , the issue should be fixed in recently released v8.4.0 🚀

**Comment by kirdk** [comment]
@RobinTail Thank you, Anna, I'll try.
