### ISSUE TITLE
Bug: Cannot set description on `dateIn` and `dateOut` fields

### ISSUE THREAD

**Issue by shroudedcode** [RobinTail/express-zod-api#672]
First of all: Great job on this library! It manages to strike an almost perfect balance between being super quick and easy to get started with while also not being too restrictive or opinionated. Kind of like tRPC but more "public-API-friendly".

Anyway, my team and I discovered a small bug in how the OpenAPI schema is being generated:

All fields with the `dateIn` or `dateOut` type don't keep the descriptions assigned using `.describe()`. Instead, they always have the description set to `YYYY-MM-DDTHH:mm:ss.sssZ`. It seems to be caused by [the `depictDateIn` and `depictDateOut` functions](https://github.com/RobinTail/express-zod-api/blob/1ab41c42b6a8ff7a95bc611015e8095130241faf/src/open-api-helpers.ts#L209-L244) not taking into account custom descriptions.

**Comment by RobinTail** [comment]
I agree. The description from `.describe()` should override the default one.

**Comment by RobinTail** [comment]
🚀  The fix released in version 8.3.3
