### ISSUE TITLE
API Routes with multiple `-` in the path breaks client library generation

### ISSUE THREAD

**Issue by TheWisestOne** [RobinTail/express-zod-api#805]
When an API route has multiple `-` in the path, for example `/api/test-this-one-out`, generating the client-side library breaks.

Specifically, the type names that are generated include all the `-` characters after the first one. My guess is there is a `replace` that should be a `replaceAll` or something along those lines

An example screenshot is attached
![Screen Shot 2023-02-09 at 4 20 36 PM](https://user-images.githubusercontent.com/83668621/217952489-752da87a-fa84-4d7c-b802-870056ba8943.png)

**Comment by RobinTail** [comment]
Thank you @TheWisestOne .
The fix released in v8.9.1 🚀
