### ISSUE TITLE
Locking package versions

### ISSUE THREAD

**Issue by jasonk** [RobinTail/express-zod-api#822]
This is basically the same issue as #178, just a new version of it.

Because express-zod-api specifies that it is only compatible with zod version 3.20.2 you will get errors if try to use it in an app that uses any other version of zod.

This is all that is needed to reproduce it:

```sh
mkdir repro && cd repro
yarn init -y
yarn add typescript zod express-zod-api

cat <<'END' > index.ts
import { z } from 'zod';
import { defaultEndpointsFactory } from 'express-zod-api';

defaultEndpointsFactory.build( {
  method: 'get',
  input: z.object({}),
  output: z.object({}),
  async handler() {},
} );
END

./node_modules/.bin/tsc ./index.ts
```

This is the error that is produced:

```
repro.ts:6:3 - error TS2322: Type 'ZodObject<{}, "strip", ZodTypeAny, {}, {}>' is not assignable to type 'IOSchema<any>'.
  Type 'ZodObject<{}, "strip", ZodTypeAny, {}, {}>' is not assignable to type 'ZodObject<any, any, ZodTypeAny, { [x: string]: any; }, { [x: string]: any; }>'.
    Types have separate declarations of a private property '_cached'.

6   input: z.object({}),
    ~~~~~
```

This happens because locking the version of `zod` means that unless every package in the project that uses zod also locks it to the exact same version, you are going to end up with a situation like this:

```sh
❯ find node_modules -type d -name zod
node_modules/zod
node_modules/express-zod-api/node_modules/zod
```

This means that the zod being used by express-zod-api is not the same as the zod being used in the rest of the app.

**Comment by RobinTail** [comment]
Hello @jasonk 
Could you please clarify:
Why are installing `zod` having `express-zod-api` that exports `z`?

It's made this way in order to extend zod with some proprietary schemas under the same namespace, like `z.file()` etc

**Comment by RobinTail** [comment]
Any updates, @jasonk ?

**Comment by RobinTail** [comment]
@jasonk , consider testing v10 should fix this issue.
More info here: #870
