### ISSUE TITLE
OpenAPI creation does not work under debugger on Windows

### ISSUE THREAD

**Issue by kirdk** [RobinTail/express-zod-api#84]
Under debugger launched in VSCode on Windows the following method:
```
const swaggerDocument = new OpenAPI({
      routing: router,
      version: '0.0.1',
      title: 'API',
      serverUrl: 'https://example.com',
}).getSpec();
```
throws the error: **_Zod type ZodObject is unsupported_**

If I run the same code from the console it works fine.

NodeJS: v14.17.3
TS: v4.2.4

**Comment by RobinTail** [comment]
Hello @kirdk ,

thank you for reaching out. 

> If I run the same code from the console it works fine.

This inconsistency looks strange.
I'm not sure whether it is related to Windows or VSCode, but let's begin with something more obvious.

Could you please check and confirm the following:
- There is no `zod` dependency in your `package.json` file, only `express-zod-api` instead.
- All your endpoints listed within `routing: router` are using `z.object()` while `{ z }` is imported from `express-zod-api`.

**Comment by kirdk** [comment]
> Hello @kirdk ,
> 
> thank you for reaching out.
> 
> > If I run the same code from the console it works fine.
> 
> This inconsistency looks strange.
> I'm not sure whether it is related to Windows or VSCode, but let's begin with something more obvious.
> 
> Could you please check and confirm the following:
> 
> * There is no `zod` dependency in your `package.json` file, only `express-zod-api` instead.
> * All your endpoints listed within `routing: router` are using `z.object()` while `{ z }` is imported from `express-zod-api`.
> 
> P.S. Do I understand correctly that the version of the library installed is `2.0.0`?

Dear @RobinTail ,

- Yes, only `express-zod-api` is used in `package.json`
- Yes, all endpoints used  in the `router` are using `z.object` as the `output`
- I confirm that the version of `express-zod-api` is `2.0.0`

Also, we checked the debugger on Linux (with exactly the same code) and it also works fine.

**Comment by RobinTail** [comment]
Thank you @kirdk .

Then I suppose the issue is related to the debugger of VSCode.

I tried the following runner on the latest version of VSCode on MacOS: `kakumei.ts-debug` with the following configuration as `.vscode/launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "ts-node",
            "type": "node",
            "request": "launch",
            "args": [
                "${relativeFile}"
            ],
            "runtimeArgs": [
                "-r",
                "ts-node/register"
            ],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```

And it works. I hope this information will prove helpful.

**Comment by kirdk** [comment]
> Thank you @kirdk .
> 
> Then I suppose the issue is related to the debugger of VSCode.
> 
> I tried the following debugger extension on the latest version of VSCode on MacOS: `kakumei.ts-debug` with the following configuration as `.vscode/launch.json`:
> 
> ```json
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "ts-node",
>             "type": "node",
>             "request": "launch",
>             "args": [
>                 "${relativeFile}"
>             ],
>             "runtimeArgs": [
>                 "-r",
>                 "ts-node/register"
>             ],
>             "cwd": "${workspaceRoot}",
>             "protocol": "inspector",
>             "internalConsoleOptions": "openOnSessionStart"
>         }
>     ]
> }
> ```
> 
> And it works. I hope this information will prove helpful.

Dear Anna,
Thank you so much!)
The option `"cwd": "${workspaceRoot}"` solved the issue.
