### ISSUE TITLE
TypeScript error 4023 when exporting middleware

### ISSUE THREAD

**Issue by toddgeist** [RobinTail/express-zod-api#963]
![CleanShot 2023-04-24 at 10 19 56](https://user-images.githubusercontent.com/316792/234070204-ed57c575-9c9b-4c0e-aa5a-39b62abfb7cf.png)

The above example is with `createMiddleware` but this happens on other other things like `defaultEnpointsFactory`. I am able to get around that one with 

`export const infoEndPoint: AbstractEndpoint = defaultEndpointsFactory.build({`

But there are no AbstractClasses or Types or Interfaces that I can find for the others.  This feels like something I am over looking.  But I can't find it.

The above example is just copy and past from the example app.

??

**Comment by RobinTail** [comment]
Hello @toddgeist .

can you disable `declaration` in your `tsconfig.json`?

**Comment by toddgeist** [comment]
That worked. Thank you!
